version: "3.9"
services:
  mongodb:
    image: mongo:8.0.10
    container_name: mongodb_boilerplate
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - boilerplate

  redis:
    image: redis:7.4.2
    container_name: redis_boilerplate
    ports:
      - "6379:6379"
    networks:
      - boilerplate

volumes:
  mongo_data:

networks:
  boilerplate:
