version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate
    ports:
      - "8000:8000"
    env_file:
      - .env.development.local

    depends_on:
      - mongodb
      - redis
    networks:
      - boilerplate

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb_boilerplate
    ports:
      - "9050:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - boilerplate

  redis:
    image: bitnami/redis:latest
    container_name: redis_boilerplate
    ports:
      - "9051:6379"
    networks:
      - boilerplate

volumes:
  mongo_data:

networks:
  boilerplate:
